### ISSUE TITLE
Update Preact integration to support partial re-renders

### ISSUE THREAD

**Issue by andy-haynes** [near/bos-web-engine#138]
Currently only the root Component within a container can request a re-render. The consequence of this is that any update to a descendant Component within a trusted Component tree causes the entire container to re-render.

A few things need to change at a minimum to address this:
- trusted Components must get an `id` attribute uniquely identifying them within the DOM tree
- the rendering logic configured in the `initContainer` closure needs to be parameterized for Components
- the `Preact.options.diffed` callback needs to identify the changed DOM and/or fire on vnodes other than the root `<Fragment>` vnode

**Comment by JoviDeCroock** [comment]
There are some ways to do this with Preact, you can use what has been described [here](https://www.jovidecroock.com/blog/preact-use-id) and what has been implemented in the [`useId`](https://github.com/preactjs/preact/blob/main/hooks/src/index.js#L395) hook. The thing y'all would have to ensure is that you add a root-identifier as you are generating a lot of Preact roots to render from. In React this is done as an argument to the `render` function but I reckon that assigning an attribute to every root and using the `options` hooks would also get you that far.

**Comment by andy-haynes** [comment]
Hey @JoviDeCroock, thanks for weighing in again!

> This means that we can uniquely identify a tree by building up the position a child-node is in the parent-children and keep that around as a mask we build up for each node.

This is actually the approach used to create a base ID for a component within a container, and for instances where it is ambiguous, we require that a unique ID is provided to augment this base ID.

However for this issue it’s looking like the problem is misunderstanding `options.diffed` and general misuse of Preact 😅. In the current implementation, renders are only requested when the vnode argument is the root component for the container. But after reworking the container Preact integration, I’m seeing that the way `options.diffed` emits nodes lets us construct the output DOM tree and request the render once the component is encountered that produced that DOM tree.

So if I have a container with a component tree like:
```
  A
 / \
B   C
```

Currently a change to B will always re-render A. Changes to B would be followed by a series of `options.diffed` executions with the following vnode argument values:
```
{ type: "div", props: { children: "this is updated content in B" } }
{ type: B, props: { id: "b", src: "components/b" } }
{ type: A }
{ type: Fragment, props: { children: [{ type: A, ... }] } } // here the render request fires with output from vnode.props.children[0].type()
```

But after reworking how the container uses Preact, the sequence of vnode argument values I'm seeing is:
```
{ type: "div", props: { children: "this is updated content in B" } }
{ type: B, props: { id: "b", src: "components/b" } } // can request here using unique ID provided to B
```

So it should just be a matter of updating the interface and outer window implementation to update subsets of a component tree. However if `options.diffed` is emitting nodes in this postorder traversal, we can't know the root of the changed subtree until nodes stop being emitted. If we request renders on each updated subtree, then deep subtrees will contain children for which renders have already been requested.

E.g. for a component tree like:
```
  A
 / \
B   C
|
D
|
E
```

Changes to B would cause `options.diffed` to execute in the order of E, D, B. When E is emitted, there's no way to know that B is the root of this subtree. Subsequently a naive implementation ends up doing this:
- E's node is emitted with its child content, and requests a render (not knowing D was also updated)
- D's node is emitted with its child content (+ E), and requests a render (not knowing B was also updated)
- B's node is emitted with its child content (+ D & E), and requests a render (not knowing that it's the root of the updated subtree)

This can be mitigated a few different ways but makes me think I'm missing something by only using `options.diffed`. Ideally when B changes, one render request would be sent with the updated DOM output for B and its descendants.

I'm still figuring this all out but I put what I have so far in #142. It doesn't handle the subtree updates yet as it still assumes the entire component tree will update on any update, so that's the next goal.

**Comment by JoviDeCroock** [comment]
`options._diff` will run in the correct order, diff will be bottom-up reporting the completion of the diff while `_diff` will be top-down initiations (`_diff` in production builds is `__b`).

**Comment by andy-haynes** [comment]
That's all super helpful, thank you!
