### ISSUE TITLE
Trusted tree on state/trust demo does not render

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#163]
On `feat/application-restructure` which is the most recent branch which successfully builds, the `TrustTree` component with `trust={{ mode: 'trusted-author' }}` does not render.

`src/StateAndTrust/Root.tsx` ↓
```
<Component
  id="trusted"
  src="bwe-demos.near/StateAndTrust.TrustTree"
  trust={{ mode: 'trusted-author' }}
  props={{ title: 'State across Trusted Components' }}
/>
```

(should be rendered on the left here)
![Screenshot 2023-12-18 at 3 13 08 PM](https://github.com/near/bos-web-engine/assets/24904709/3b28f6f0-56f7-4fc3-8240-b1826191514a)

**Comment by andy-haynes** [comment]
There are a couple things in `feat/demos-with-export` preventing this from working:
- missing `props` arguments (`props` has global scope currently so referencing it is still valid 😞)
- `export function` should be `export default function` in the current implementation - I ended up restricting the valid export syntax to require `default` to disambiguate the export semantics

I've made these changes in the feature branch 👍
