### ISSUE TITLE
Consider converting each component DOM in outer window application to Shadow DOM root

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#167]
https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM

We could get some CSS encapsulation OOTB with Shadow DOM, so this might be a better solution to #8 than just selector nesting

**Comment by andy-haynes** [comment]
When testing out this approach I had issues timing the rendering of the React Component with the element unmounting occurring when the shadow DOM is attached. With the current approach of rendering React DOM roots, the closest I got was an irritating render/unmount/remount.

I think it could be worth revisiting if we find selector nesting to be untenable, but it likely requires reworking our current approach to rendering in the outer window.
