### ISSUE TITLE
Switch to pnpm 8

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#187]
Depending on which installation method you use for pnpm, you may get a different version. I was using the [corepack install](https://pnpm.io/installation#using-corepack) which yields pnpm 7.X whereas Caleb used the npm install method which yields 8.x

We should all be on the same version to create the same lockfile format, so we might as well be on the latest.

If you do not have pnpm 8.x, please uninstall then install it via `npm i -g pnpm` instead

I was able to uninstall with `corepack disable`

**Comment by andy-haynes** [comment]
Addressed in #190 🎉
