### ISSUE TITLE
Sandbox: Publishing support

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#204]

**Comment by calebjacob** [comment]
This ticket includes:

- Create a `packages/wallet-selector-control`
- Pass your own Wallet Selector instance into this component as a prop
- Set up this component in both `apps/sandbox` and `apps/web`
- Pass your own Wallet Selector instance into `<Sandbox />`
- Inside the `packages/sandbox` component, handle all UI/UX to publish to Social DB namespace (we can use "widget" for the short term until we settle on one).
- Attempt to support batch publishing (view all file diffs and select files to publish in modal).
- If batch publishing is going to take too much time, we can opt for a simpler single file publish (view and click for each file - one at a time).

**Comment by calebjacob** [comment]
Related: https://github.com/near/bos-web-engine/issues/91#event-11504122072
