### ISSUE TITLE
Use `import` syntax for BOS components and support relative path mapping

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#219]
_Originally posted by @andy-haynes in https://github.com/near/bos-web-engine/issues/205#issuecomment-1899423999_

> The ./ syntax should also help developers connect with the concept of this component being loaded locally.

Re: relative paths as Component source, I think this would be very intuitive if we adopted the import syntax I brought up offline, e.g.:
```jsx
<Component src="bwe-demos.near/Message" />
```
becomes
```jsx
import Message from "near://bwe-demos.near"; // always on chain
...
<Message />
```
or in this case
```jsx
import Message from "./Message"; // follows appropriate resolution order for environment
...
<Message />
```

I think this syntax would fit the use of relative imports really well. Relative imports would also be huge for portability, bridging the gap between web and local IDEs - imagine a `Run in Near IDE` button on GitHub repos for BWE projects 😍

**Comment by mpeterdev** [comment]
How should we handle directory↔︎dot mapping as it has been implemented thus far?

Currently, if I maintain my components in a directory structure then deploy on chain, we get something like this
`Posts/Feed/Comment.tsx` → `<author>/Posts.Feed.Comment`

The most natural is to switch Web Engine to expecting directory syntax and let the dot notation be an underlying implementation detail of SocialDB. Any concerns with this approach?
`import Comment from ./Posts/Feed/Comment`

Alternatives which don't feel great but are more in line with the data:
`import Comment from ./Posts.Feed.Comment`
`import Posts.Feed.Comment from ./Posts.Feed.Comment`

**Comment by mpeterdev** [comment]
We need to support `import _ as _` syntax to handle component name collisions

**Comment by andy-haynes** [comment]
> Any concerns with this approach?

None here, I think this is a pretty natural convention that doesn't seem too opinionated.
