### ISSUE TITLE
Generate unique class names for CSS

### ISSUE THREAD

**Issue by calebjacob** [near/bos-web-engine#252]
In the long term, it would be great to have legitimate CSS Module support and syntax like so:

```tsx
import s from './MyComponent.module.css';

export function MyComponent() {
  return <div className={s.foobar}>...</div>;
}
```

That might not be feasible in the short term, but we still need to figure out a way to make our CSS class names unique. This is typically handled by Post CSS: https://github.com/madyankin/postcss-modules

Without making our runtime classes unique, you'll end up writing styles that leak into child components - defeating the biggest benefit of CSS Modules.

Check out the following example where two separate components use the same class name of `wrapper`. The parent component applies a `padding: 1rem`, which then applies to the child that also happens to use the same `wrapper` class. The child ends up with "double padding" since it's inheriting the `padding: 1rem` from the parent.

<img width="855" alt="Screen Shot 2024-02-05 at 3 57 48 PM" src="https://github.com/near/bos-web-engine/assets/1475067/4074ae5f-4a81-4262-94a9-cd7da8e239d8">
<img width="878" alt="Screen Shot 2024-02-05 at 3 57 41 PM" src="https://github.com/near/bos-web-engine/assets/1475067/bc88820d-0a94-4449-b653-192a4683dc43">

**Comment by calebjacob** [comment]
@andy-haynes Turns out parent classes are actually taking priority and overriding child classes that overlap as well (which makes the need for unique class names even more important):

<img width="815" alt="Screen Shot 2024-02-05 at 4 30 22 PM" src="https://github.com/near/bos-web-engine/assets/1475067/34394b62-78c3-4a35-8504-5bdeaa325cdd">

The child `wrapper` should have a `gap: 0.5rem` - but the parent `wrapper` is overriding it to be `gap: 1rem`.

**Comment by mpeterdev** [comment]
@andy-haynes this is the facet of the implementation for which I initially suggested that all component css scopes start with a reset. Would that be along the right lines @calebjacob ?
