### ISSUE TITLE
🔷 [Epic] Support CSS Nesting

### ISSUE THREAD

**Issue by calebjacob** [near/bos-web-engine#253]
CSS recently added native support for nesting styles:

```css
.foo {
  button {
    &:hover { ... }
  }
}
```

The only catch is that browsers have only recently started to support it: https://caniuse.com/css-nesting

For the next year or two, it's still considered best practice to use something like Post CSS to convert the nested syntax for full browser support: https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting#readme

We also need to somehow update the Monaco CSS language parser to support nesting. We could possibly cheat and switch it to `SCSS` under the hood to support nesting syntax. Otherwise, Monaco shows a bunch of red squigglies when using nested syntax.
```[tasklist]
### Tasks
- [ ] https://github.com/near/bos-web-engine/issues/277
- [ ] https://github.com/near/bos-web-engine/issues/295
```

**Comment by mpeterdev** [comment]
may be related to #22 since a solution there would likely cover transforms a la Post CSS
