### ISSUE TITLE
`Uncaught RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#265]
Encountered this error while working on an npm compatibility overview component

Test component code:
```tsx
interface PackageCompatibility {
  name: string;
  demoLink: string;
  note?: JSX.Element | string;
}

const notCompatible: PackageCompatibility[] = [
  {
    name: 'Zustand',
    demoLink: '/bwe-demos.near/NPM.Zustand?showCode=true',
    note: (
      <span>
        BOS Web Engine plans to support cross-component global state management:{' '}
        <a href="https://github.com/near/bos-web-engine/issues/18">#18</a>
      </span>
    ),
  },
];

export function BWEComponent() {
  return (
    <>
      <PackageSection packages={notCompatible} />
    </>
  );
}

function PackageSection({ packages }) {
  return <>{packages.map(p => {
    return <div>{p.note}</div>
  })}</>
}
```

**Comment by andy-haynes** [comment]
While serializing props to `PackageSection` it tried to traverse the Preact node as a POJO, but nodes are self-referential 😄 

I have it working locally but I'm going to check out a few related cases to make sure we're covered. In particular functions that use Preact and BWE Components as arguments and returned values.

**Comment by andy-haynes** [comment]
I couldn't find any other issues around Components so this was just a gap in coverage.

It actually would have worked if the `note` prop was a function returning the Component, it was only props serialization that wasn't taking that case into account.
