### ISSUE TITLE
Local development tooling (e.g. bos-loader)

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#28]

**Comment by mpeterdev** [comment]
@andy-haynes do you already have a method for loading component code that doesn't require saving each change on chain? If not, I think it makes sense for me to knock this out since it would be useful during BWE testing/development

**Comment by andy-haynes** [comment]
Nope, the current implementation only knows how to pull the source down.

This is the method responsible for fetching from RPC and caching the source: https://github.com/near/bos-web-engine/blob/main/packages/compiler/src/compiler.ts#L46

Overriding the behavior there would let you bypass the RPC fetch and caching altogether.
