### ISSUE TITLE
Access current accountId context

### ISSUE THREAD

**Issue by calebjacob** [near/bos-web-engine#311]
The current VM allows you access a global variable `context` which provides an `accountId` value of the currently signed in user/wallet (it's `null` if the user isn't signed in). Many components and flows require access to this `context.accountId` value.

Now that we have the Wallet Select Plugin, I wonder if something like this could make sense:

```tsx
import { getWalletSelectorState } from '@bos-web-engine/wallet-selector-plugin';

export default function () {
  const wallet = getWalletSelectorState(); // Returns null or WalletSelectorState
  const account = wallet?.accounts[0];
  const accountId = account?.accountId;

  return (
    <div>
      You are signed in as: {accountId}
    </div>
  );
}
```

You can refer to `useWallet.ts` for an example of interacting with `WalletSelectorState`.

**Comment by calebjacob** [comment]
@mpeterdev Would this make sense as a quick follow up for next sprint?

**Comment by mpeterdev** [comment]
great catch, we should absolutely prioritize this
