### ISSUE TITLE
Send NEAR demo sends 0 NEAR

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#321]
I tried sending 1 NEAR through the `signAndSendTransaction` demo component and the printed result shows 1 being sent but the transaction in Meteor Wallet's confirmation and nearblocks.io both show a transfer of 0 NEAR

Printed result
![Screenshot 2024-02-23 at 10 55 33 AM](https://github.com/near/bos-web-engine/assets/24904709/53de7a71-6039-4a61-9f41-59d6c2994b56)

nearblocks.io transaction
https://nearblocks.io/txns/5f3YyEPAhAhsCuWPTJ7EQueNXauvUNGkdgVnjJbK947r

Transaction confirmation prompt in Meteor Wallet(not the same attempt as above, forgot to take screenshot first time)
![Screenshot 2024-02-23 at 10 55 50 AM](https://github.com/near/bos-web-engine/assets/24904709/7a287b32-fd13-48b7-8779-1d72b7755b2f)

**Comment by andy-haynes** [comment]
> I tried sending 1 NEAR

Correction, you tried to send 1 _yocto_NEAR 😄
