### ISSUE TITLE
Fork components QueryAPI indexer for component_alpha namespace

### ISSUE THREAD

**Issue by calebjacob** [near/bos-web-engine#338]
The current `components` indexer only tracks the `widget` namespace. We should fork it so we can track activity on the `component_alpha` namespace.

**Comment by mpeterdev** [comment]
short term goal is to get insight into alpha testing activity

**Comment by calebjacob** [comment]
I finished publishing and backfilling a fork of the components indexer here: https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=calebjacob.near%2Fcomponents_alpha
