### ISSUE TITLE
Handle syntax lowering for modern CSS

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#364]
should be addressed by #280 if configured as here: https://lightningcss.dev/transpilation.html#syntax-lowering

**Comment by andy-haynes** [comment]
Is SASS a viable solution? https://sass-lang.com/blog/sass-in-the-browser/

**Comment by klngrs** [comment]
I was learning about the current Near VM and stumbled upon this repository. I have a simple PR for this if you're interested!

**Comment by andy-haynes** [comment]
Hey @klngrs thanks for the interest! Are you able to fork this repo and open the PR in the forked branch to target this repo's `main` branch?

**Comment by klngrs** [comment]
No problem!
