### ISSUE TITLE
`bos-loader` Components get fetched from RPC

### ISSUE THREAD

**Issue by andy-haynes** [near/bos-web-engine#382]
Before #360 when rendering local Components in `demos` via `bos-loader`, the local version was used to populate the cache and it was never fetched from Social DB. Now it appears that the Component is set initially, but the fetch is made anyway. For Components that don't exist on chain (e.g. in `/ignore`), this triggers an error that persists on the page.

Console screenshot, note the second RPC fetch:
![image](https://github.com/near/bos-web-engine/assets/36863574/af24baa0-5cb1-4e1c-9427-565d1c06319a)

**Comment by mpeterdev** [comment]
need to dedupe compiler for web

**Comment by andy-haynes** [comment]
This issue is fixed with #385 but the underlying problem is that the compiler is processing requests before it's finished initializing, which is likely why sandbox still tries to fetch newly-added Components. I'll file a separate issue for this.
