### ISSUE TITLE
`in` operator breaks transpilation in Vercel builds

### ISSUE THREAD

**Issue by andy-haynes** [near/bos-web-engine#47]
Seen after porting to transpilation to a web worker from an iframe. Works fine locally, only seems to be an issue in Vercel builds.

> This works fine for me locally but for some reason the deployed version seems to have a bug in Babel - it doesn't recognize the `in` keyword as valid JS syntax:
![image](https://github.com/near/bos-web-engine/assets/36863574/0bab8570-bba4-404b-9e03-3c84fff49176)

https://github.com/near/bos-web-engine/pull/40#issuecomment-1707101559

**Comment by mpeterdev** [comment]
may be resolved by #57

**Comment by andy-haynes** [comment]
No longer applicable
