### ISSUE TITLE
SWC for outer application transpilation

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#65]

**Comment by mpeterdev** [comment]
@andy-haynes any reason we are using babel for Next.js transpilation over SWC which is now the default for Next.js? It doesn’t look like we have anything special configured for it so I will go ahead and remove `.babelrc` to revert to default behavior if not

**Comment by andy-haynes** [comment]
It's almost certainly a holdover from when I was trying to do transpilation of Widget bodies in the outer application. It can go for sure 👍 

I'll create an issue for using SWC in `compiler` as well.

**Comment by mpeterdev** [comment]
should be resolved by #74 since `.babelrc` was removed. Needs confirmation
