### ISSUE TITLE
Sandbox page in Vercel deployment

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#86]
Create a page with an embedded Monaco or CodeMirror editor and BWE instance which renders the contents for anyone to play with the BWE deployment

**Comment by charleslavon** [comment]
@calebjacob let's consider this one for an upcoming sprint. This effort to create a BWE-based IDE for short-term use, would help us understand what will be needed to build a production ready version for near.org, even if the code we write here is not entirely reusable.  Or, another path we can consider to take is to write this editor in React, get some usage on it, and then possibly port it to be a BWE BOS component.

**Comment by mpeterdev** [comment]
one of the primary tasks here will be determining how to have BWE consume code from the editor since the `useWebEngine` hook does not currently accept arbitrary code like the VM `<Widget />` does

**Comment by calebjacob** [comment]
Our primary focus for this MVP:

- Overall UI layout (sidebar file navigator, editor)
- Ability to write code in an editor (Monaco/CodeMirror)
- Render and preview code output

Potentially in scope:

- Capable of creating, editing, and switching between multiple files/tabs. Files would not be able to reference each other at this stage.

Out of scope (quick follow up items):

- Files can reference each other (render `ComponentB.tsx` inside `ComponentA.tsx`). Would respect local changes over published version.
- Publish/save components

**Comment by calebjacob** [comment]
Potential UI layout inspiration:

![Screenshot 2024-01-04 at 4 37 56 PM](https://github.com/near/bos-web-engine/assets/1475067/910b9417-251c-4bb4-b72f-3ccfa6e3e18f)

**Comment by mpeterdev** [comment]
Potentially relevant: I have worked with `Sandpack`, the IDE toolkit created by CodeSandbox, in the past and found it to be friendly. I am unsure if it would make sense to leverage here since a core piece of Sandpack is the bundler/preview which we would not need since that is handled by BWE.

It works a bit like Radix where you can take their subcomponents and construct them to meet your needs

e.g.
```tsx
import {
  SandpackProvider,
  SandpackLayout,
  SandpackPreview,
  SandpackCodeEditor,
} from "@codesandbox/sandpack-react";

export default () => (
  <SandpackProvider template="react">
    <SandpackLayout>
      <SandpackCodeEditor
        showTabs
        showLineNumbers={false}
        showInlineErrors
        wrapContent
        closableTabs
      />
      <SandpackPreview />
    </SandpackLayout>
  </SandpackProvider>
);
```

In this case, `SandpackPreview` is the bundler/renderer which we don't need. If you dropped that out, you would have a lot of the UI we're looking for and a slot to place the BWE preview. I know `SandpackProvider` is responsible for handling IDE state which could be a helpful starting point for us, but it might also have a lot of weight we don't need if its built specifically for use with the `SandpackPreview`

Components of note:
[Code Editor](https://sandpack.codesandbox.io/docs/advanced-usage/components#code-editor)
[File Explorer](https://sandpack.codesandbox.io/docs/advanced-usage/components#file-explorer)
![Screenshot 2024-01-04 at 5 05 12 PM](https://github.com/near/bos-web-engine/assets/24904709/a0eaad3b-83f6-4073-a8c6-8bd131b5a01b)

If the UI components don't meet our needs, using just the provider and its [hooks](https://sandpack.codesandbox.io/docs/advanced-usage/hooks) to power our custom components could be another approach

If nothing else, these docs might serve as inspiration 😄

**Comment by calebjacob** [comment]
Related to TypeScript intellisense/autocomplete: 

-CodeSandbox actually uses Monaco: https://discuss.codemirror.net/t/codemirror-6-and-typescript-lsp/3398/35
- Here’s the best Sandpack TS Server integration I’ve seen so far: https://codesandbox.io/p/sandbox/github/danilowoz/sandpack-tsserver/tree/main/?file=%2Fsrc%2Fsandpack-components%2FCodeEditor.tsx%3A8%2C6-8%2C16

**Comment by mpeterdev** [comment]
after discussion with @calebjacob, we will be moving forward with Sandpack but with Monaco swapped in as the editor to provider better language support and intellisense

A difficult aspect of editor support in this context is arbitrary dependencies. When using a code editor locally, it is able to reference installed NPM packages for types and APIs. In the BWE component context where an author can import any NPM package and we fetch it behind the scenes from esm.sh, there is simple way to provide type and intellisense support for those libs.

We may explore an implementation down there line where we have a process in the Sandbox react component which listens to Sandpack for file changes and upon encountering code with a new import statement we kick off a direct fetch from esm.sh and then inject the response into Monaco

**Comment by calebjacob** [comment]
So after switching over to using Monaco, it quickly became apparent that Sandpack wasn't providing much value. The `FileExplorer` component wasn't capable of supporting renaming/deleting files. Also, adding a new file wasn't behaving correctly with their provider/state (there's a bug related to how they handle hidden files).

Turns out it was really easy to re-implement what Sandpack was providing via Zustand + Radix. Now we have even more flexibility and control with less dependencies.

Sandpack did help give inspiration and a really early starting point - so I'll credit it for that. :)
