### ISSUE TITLE
Evaluate package repositories for importing arbitrary dependencies (npm CDN comparison)

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#93]
Output: discussion thread

**Comment by mpeterdev** [comment]
- https://www.unpkg.com/
- https://esm.sh/
- https://www.skypack.dev/
- https://jspm.io/
- https://www.jsdelivr.com/

**Comment by andy-haynes** [comment]
`esm.sh` appears to be the best option for us, at least in the short term. Notably it provides bundling and supports React aliasing and dependency versioning, which allow us to directly import modules bundled with the same version Preact loaded in the container. Without these we would need to handle bundling ourselves in the compiler web worker currently responsible for building container code.

In the long term, it's very likely we'll want to explore optimizations around bundling BOS Components, at which point we can explore bundling alternatives to support generic providers who serve up versioned modules directly. In the interim, `esm.sh` is ideal to get us up and running at the expense of having a single upstream point of failure.

- `unpkg.com` provides minimal options. If a known compatible bundle is available from a path within that package source (e.g. within `/dist`), then this could be a viable option.
- `skypack.dev` provides browser-optimized packages and offers more options than `unpkg.com`, but no bundling capabilities.
- `jspm.io` has similar capabilities to `unpkg.com` with no bundling capabilties.
- `jsdelivr.com` bills itself as hyper available, making use of multiple CDNs to serve traffic; it has no bundling capabilities

**Comment by andy-haynes** [comment]
Closing this for now since we have a solution in place, but I'm sure there will be more to discuss and revisit later on.
