### ISSUE TITLE
🔷 [Epic] Support component versioning by blockheight

### ISSUE THREAD

**Issue by mpeterdev** [near/bos-web-engine#95]
## Description
Parity feature

When embedding another BOS component, it should be possible to provide a blockheight at which a version of that component was published in order to lock to that version

Providing a blockheight which does not correspond to a publish should throw an error

Syntax does not need to match VM implementation

## Resources

1. [VM implementation](https://github.com/NearSocial/VM/pull/18)

**Comment by mpeterdev** [comment]
we may wish for default behavior to differ from the VM implementation, see https://github.com/NearSocial/VM/discussions/102

**Comment by mpeterdev** [comment]
@andy-haynes 
if we move to default version locking, we could do some interesting performance optimizations where the metadata of a component includes an array of all down-tree components such that when loading a root component we may only need to do one subsequent bulk source fetch to get the remainder of the components which will be rendered. This would likely require static analysis at time of writing the component, and it may not be perfect, but even a best effort could lead to significantly less request waterfall during load

**Comment by andy-haynes** [comment]
That could be a massive improvement for loading across the board.

It would be pretty straightforward to use the same tree parsing logic in both places (for setting the metadata and parsing Components without metadata).

**Comment by mpeterdev** [comment]
@gabehamilton Am I correct that it would be most effective to power a fetch like this via Query API since we would be aggregating data across a number of SocialDB keys and blockheights?

**Comment by mpeterdev** [comment]
we'll move forward with this with a pure SocialDB `get` implementation and consider QueryAPI usage when we get to performance optimizations

**Comment by gabehamilton** [comment]
Sounds good. The components indexer is populated. They can be fetched [here](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fnear-queryapi.api.pagoda.co%2Fv1%2Fgraphql&header=x-hasura-role%3Adataplatform_near&query=query+MyQuery+%7B%0A++dataplatform_near_components_versions%28%0A++++where%3A+%7Bcomponent_author_id%3A+%7B_eq%3A+%22near%22%7D%2C+component_name%3A+%7B_eq%3A+%22AccountAutocomplete%22%7D%2C+block_height%3A+%7B_eq%3A+107226941%7D%7D%0A++%29+%7B%0A++++code%0A++++component_name%0A++++component_author_id%0A++++block_height%0A++%7D%0A%7D%0A)

like
```
query ComponentByBlockheight {
  dataplatform_near_components_versions(
    where: {component_author_id: {_eq: "near"}, component_name: {_eq: "AccountAutocomplete"}, block_height: {_eq: 107226941}}
  ) {
    code
    component_name
    component_author_id
    block_height
  }
}
```

**Comment by mpeterdev** [comment]
likely implemented by supporting `import MyComponent from near://michaelpeter.near/MyComponent@<blockheight>`

**Comment by mpeterdev** [comment]
https://t.me/c/1881788227/46
